### ISSUE TITLE
MMB click to center view

### ISSUE THREAD

**Issue by DrezzyJ** [daniluk4000/vatsim-radar#100]
### Your Vatsim CID

1809808

### What do you suggest?

Using a middle mouse button press to center the view on the map

### Why do you need that?

A small QoL update. To view what I am talking about, see how VATSpy does it.

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Will be added in 0.4.2
