### ISSUE TITLE
Maastricht Radar not displayed

### ISSUE THREAD

**Issue by medibasti05** [daniluk4000/vatsim-radar#104]
### Your Vatsim CID

1558088

### Radar version

0.4.1

### Describe your issue

Maastricht Radar not displayed. EDYY_S_CTR 

### Reproduction steps

Open Webbrowser

### Platform

windows

### Validation

- [x] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned
- [ ] I am QA or Patreon member and using next.vatsim-radar.com
- [X] I couldn't reproduce it on production / it's issue in new functionality

**Comment by daniluk4000** [comment]
This isn't next version, so I'm removing this tag

**Comment by medibasti05** [comment]
oh sorry

**Comment by daniluk4000** [comment]
Closing in favor of https://github.com/daniluk4000/vatsim-radar/issues/105
