### ISSUE TITLE
Approach info not properly showing when hovering

### ISSUE THREAD

**Issue by fdrake97** [daniluk4000/vatsim-radar#106]
### Your Vatsim CID

1664386

### Radar version

0.4.1

### Describe your issue

When hovering over Approach controller, the info does not show as well as it does on all other stations. Sometimes when zoomed out it doesn't show at all, or when hovering it seems the mouse needs to be nin a certain position for it to work. Basically it isn't as seamless and snappy as with the other stations.

https://github.com/daniluk4000/vatsim-radar/assets/87662019/8188e0cd-4baa-41b3-936d-7c60cda596b4

### Reproduction steps

Hover over any approach, especially when slightly zoomed out. Compare to hovering over any cab or center position.

### Platform

Windows 11, chrome.

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Should be much better in 0.4.2
