### ISSUE TITLE
NorCal Approach missing

### ISSUE THREAD

**Issue by DrezzyJ** [daniluk4000/vatsim-radar#109]
### Your Vatsim CID

1809808

### Radar version

v0.4.2-alpha.2

### Describe your issue

NorCal approach missing

### Reproduction steps

Scroll over to KSFO area and you won't see NorCal approach on
![NorCal](https://github.com/daniluk4000/vatsim-radar/assets/169841916/345964d8-ac4c-4072-a479-56b0f3f2a84e)
![NorCalMISSING](https://github.com/daniluk4000/vatsim-radar/assets/169841916/2a9b319c-2dde-4634-babf-5bfcde678d29)

First photo is production version, second is the beta

### Platform

windows

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned
- [X] I am QA or Patreon member and using next.vatsim-radar.com
- [x] I couldn't reproduce it on production / it's issue in new functionality

**Comment by DrezzyJ** [comment]
Same issue as: https://github.com/daniluk4000/vatsim-radar/issues/96

Sorry, this can be closed

**Comment by daniluk4000** [comment]
Nah it's ok

Please tell me the callsign

**Comment by DrezzyJ** [comment]
> Nah it's ok
> 
> Please tell me the callsign

NCT_APP
