### ISSUE TITLE
SoCal APP is missing

### ISSUE THREAD

**Issue by Vainnor** [daniluk4000/vatsim-radar#111]
### Your Vatsim CID

1652726

### Radar version

v0.4.2-alpha.2

### Describe your issue

SoCal APP (SCT_APP) Is not on next.vatsim-radar however it is on vatsim-radar

This is vatsim-radar.com
![image](https://github.com/daniluk4000/vatsim-radar/assets/142100426/91e2d9f9-298b-43be-acaf-7cb84837b916)

This is next.vatsim-radar.com

![image](https://github.com/daniluk4000/vatsim-radar/assets/142100426/7ab2387f-056b-4c00-993e-22c1158c4966)

This is vatprism

![image](https://github.com/daniluk4000/vatsim-radar/assets/142100426/9718eb10-dc29-4b1d-9071-52c6a9b2efd7)

### Reproduction steps

Scroll over to KLAX area and you won't see SoCal approach on

### Platform

Windows, Brave Version 1.67.119 Chromium: 126.0.6478.114 (Official Build) (64-bit)

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned
- [X] I am QA or Patreon member and using next.vatsim-radar.com
- [X] I couldn't reproduce it on production / it's issue in new functionality

**Comment by daniluk4000** [comment]
Will be fixed next build
