### ISSUE TITLE
Flightpath drawn after disconnection with different callsign

### ISSUE THREAD

**Issue by GermainDeDuck** [daniluk4000/vatsim-radar#112]
### Your Vatsim CID

1696195

### Radar version

 v0.4.2-alpha.2

### Describe your issue

I am doing a long haul flight from EGLL to WSSS, during this long haul I went to sleep so I disconnected. About 10 hours later, I reconnected (with a different callsign as my old one was taken), yet the tracker drew a straight line across all of EU to my new position with the new callsign. 

Orginal callsign: SIA318
New callsign: SIA315

![Screenshot 2024-06-27 111329](https://github.com/daniluk4000/vatsim-radar/assets/104932018/217188a6-d9ad-499a-9cb3-66a03c95ffe3)

### Reproduction steps

Do a flight as normal, but somewhere airborn disconnected.
Then a bit later, reconnect again in air with a different callsign.

### Platform

Windows - Google Version 126.0.6478.127 (64 bit)

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned
- [X] I am QA or Patreon member and using next.vatsim-radar.com
- [X] I couldn't reproduce it on production / it's issue in new functionality

**Comment by daniluk4000** [comment]
Will be available in "next" build
