### ISSUE TITLE
PCT Combined Not Displayed with SHD Sector Open

### ISSUE THREAD

**Issue by Giantpickle314** [daniluk4000/vatsim-radar#119]
### Your Vatsim CID

1545737

### Radar version

0.4.2-alpha.2

### Describe your issue

![image](https://github.com/daniluk4000/vatsim-radar/assets/114345293/1fa46d50-80c2-49fb-b9f5-2d456d63da00)
With the Shennandoah Sector open (Covering IAD), the combined Potomac Sector (Covering the remaining of IAD, DCA, and BWI) is not displayed on the Next version. It is displayed on the standard version. Issue persists after reloading.

### Reproduction steps

With the Shennandoah Sector open, Potomac Combined is not displaying. I believe that Potomac Combined has displayed correctly in the past, so I assume this is related to having one position of a combined sector open as well as the combined sector.

### Platform

Windows 11, Vivaldi 6.8.3381.46 (Stable channel) (64-bit) 

### Additional info

This may be related to the SoCal issue brought up here, but those were separate sectors rather than a combined/separate issue. https://github.com/daniluk4000/vatsim-radar/issues/111 

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned
- [X] I am QA or Patreon member and using next.vatsim-radar.com
- [X] I couldn't reproduce it on production / it's issue in new functionality

**Comment by daniluk4000** [comment]
Yes, should be fixed next version
