### ISSUE TITLE
Las vegas airport is still called "McCarren International" while it got changed to "Henry Reid international" 2 years ago

### ISSUE THREAD

**Issue by epicryder05** [daniluk4000/vatsim-radar#123]
### Your Vatsim CID

1676850

### Radar version

v0.4.1

### Describe your issue

Las Vegas main airport got changed to "Henry Reid" after the death of the  senator in 2021 while its still called McCarren on vatsim radar.
![image](https://github.com/daniluk4000/vatsim-radar/assets/174272226/4293f6d0-7ce3-463c-a006-6b28370b38f8)

### Reproduction steps

Hover over KLAS when there's tower or activity there

### Platform

windows 10 browser

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
This should be fixed on VatSpy side by some of local stuff.

![image](https://github.com/daniluk4000/vatsim-radar/assets/10450717/bc3de45f-1416-45bf-8957-f2727b5d2ba9)

I can help with submitting a request, but it has to be approved by locals.
