### ISSUE TITLE
Middle mouse click on active controllers breaks/freezes map

### ISSUE THREAD

**Issue by DrezzyJ** [daniluk4000/vatsim-radar#125]
### Your Vatsim CID

1809808

### Radar version

v0.4.2-alpha.3

### Describe your issue

When using middle mouse click to center map, if you click on an active ATC controller, the map blanks out and freezes. See photo below:

BEFORE
![image](https://github.com/daniluk4000/vatsim-radar/assets/169841916/a1817fc6-e65c-4e4f-a48f-0122a823b6d3)

AFTER
![image](https://github.com/daniluk4000/vatsim-radar/assets/169841916/69fc987f-5bf7-4203-ad8d-e157c34a88d2)

### Reproduction steps

1) Use middle mouse click
2) Click on any active ATC controller

### Platform

Windows/Chrome

### Additional info

Does not break if you middle mouse click an aircraft

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Wtf haha
