### ISSUE TITLE
Add ability to zoom into map when hovering on ATC info.

### ISSUE THREAD

**Issue by fdrake97** [daniluk4000/vatsim-radar#126]
### Your Vatsim CID

1664386

### What do you suggest?

Title

### Why do you need that?

Currently it is difficult to zoom into areas with a lot of ATC and ATIS online, such as NYC. Or, if you want to go to an airport with ATC coverage and you want to zoom in, it's a bit annoying because you put your mouse on the spot you want to zoom to, but it hovers on the ATC and you can't. I think it would be easier if you could zoom while hovered on the ATC info.

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
If I made this work, if this window has a scroll you won't be able to scroll. 

This "lock" is disabled when you are currently zooming (while you continue to zoom). Also hover is disabled on high level zoom. 

Also if I disable lock, yiou won't be able to select text in this popup. I believe that current behaviour is fine - but we can also improve it. If you have another ideas - please tell me :)

**Comment by fdrake97** [comment]
Seems like a fair compromise. Thanks for considering!
