### ISSUE TITLE
Simulator Information

### ISSUE THREAD

**Issue by Erdemes** [daniluk4000/vatsim-radar#143]
### Your Vatsim CID

961835

### What do you suggest?

Hello, is it possible to show the simulator that the pilot is using in the flight information panel, such as MSFS, XP12, P3D? And maybe in the controller page next to the callsign just like pilot stats.

### Why do you need that?

Sometimes as a controller I want to know which simulator the pilot is using because I can know his pushback ability or some known scenery differences between simulators.

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Impossible, sorry
