### ISSUE TITLE
Add current Zulu time in Controller view

### ISSUE THREAD

**Issue by dellop** [daniluk4000/vatsim-radar#145]
### Your Vatsim CID

1519013

### What do you suggest?

Show the current Zulu time in Controller mode.

### Why do you need that?

It allows for quick reference on arriving aircraft if not displayed elsewhere.

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Uh, where should I add it?

**Comment by dellop** [comment]
![Screenshot 2024-07-09 125620](https://github.com/daniluk4000/vatsim-radar/assets/35943520/69ab2c94-9584-46bf-89d4-ee7673833b5a)
Maybe in this red box? No, just the current Zulu time.

**Comment by daniluk4000** [comment]
Got you. Not there, but copied

**Comment by dellop** [comment]
![Screenshot 2024-07-09 125844](https://github.com/daniluk4000/vatsim-radar/assets/35943520/edae7682-00cf-42f3-aad2-fa40348925eb)
Maybe similar to this - this is no frills, just a suggestion.
