### ISSUE TITLE
Colons are stripped from controller info

### ISSUE THREAD

**Issue by neilenns** [daniluk4000/vatsim-radar#147]
### Your Vatsim CID

1525628

### Radar version

v0.4.2-rc.2

### Describe your issue

When clicking on a controller to see their details any colons that were in the original controller info are removed.

### Reproduction steps

1. Find a controller somewhere that knows they put colons in their controller info, e.g. mine

![image](https://github.com/daniluk4000/vatsim-radar/assets/9524118/a3edc2e0-d3b8-4b7d-b758-a5e06234ec0e)

2. Click on the controller to see their details. The colons are missing.

![image](https://github.com/daniluk4000/vatsim-radar/assets/9524118/79947abe-14d9-4d9d-9343-38964792c7e6)

### Platform

Windows 11, Edge

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
API bug
