### ISSUE TITLE
Allow selection of multiple airports at once

### ISSUE THREAD

**Issue by glott** [daniluk4000/vatsim-radar#159]
### Your Vatsim CID

redacted

### What do you suggest?

Allow multiple airport information to be viewed at once (maybe up to 3). The most recently selected one would be on the bottom and expanded. 
![image](https://github.com/daniluk4000/vatsim-radar/assets/5761158/24226d6d-3861-490a-b921-da226b033c5c)

### Why do you need that?

Being able to see multiple airports provides more information about what is happening around a certain area. 

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
![image](https://github.com/daniluk4000/vatsim-radar/assets/10450717/32692a05-6f36-4f4b-a371-489e1207ea58)

You have pin icon though for that
