### ISSUE TITLE
Add to Friends/Follow someone

### ISSUE THREAD

**Issue by hwisniewski1** [daniluk4000/vatsim-radar#173]
### Your Vatsim CID

1690829

### What do you suggest?

Like on IVAO Webeye add ability to add friends and then display tab when you can check if they are flying or controlling

### Why do you need that?

It is good to see if your friend is flying to fly with them, ask to make a next flight both. It will also allow you to check if friend is controlling and where so you can fly to him.

### Additional info

I dont think it is must-have but it would be great if you consider it and think about it after main steps

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Nope. It will be coming first Stage 3 update. We need this haha

And it's in roadmap

**Comment by hwisniewski1** [comment]
ohhh, i missed it sorry
