### ISSUE TITLE
Match COM1 with associated controller

### ISSUE THREAD

**Issue by DotWallop** [daniluk4000/vatsim-radar#178]
### Your Vatsim CID

1227980

### What do you suggest?

As you are able to identify nearby controllers per aircraft, you should also have their frequencies. It would be a bit easier for everyone to quickly see what station the user is tuned into, if you match the frequency to an active station nearby. It has to be geo-limited to not have conflicting frequencies. Perhaps also making COM1 clickable if it discovers an active station, that opens the station view.

![image](https://github.com/user-attachments/assets/2dd72870-889f-4f89-b5ab-ed5074b3cb7a)
UI display something like "121.55 (ENOR_S_CTR)" either next to, or as a separate line above or below. :)

### Why do you need that?

A bit easier to navigate and match frequencies when looking at COM1.

### Alternatives

Manually having to open the station and look for its frequency

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by FX5F** [comment]
Sometimes stations have cross coupled multiples frequencies. So you can't rely only on the primary frequency. Not sure if the data contains the additional frequencies.

**Comment by daniluk4000** [comment]
> Sometimes stations have cross coupled multiple frequencies. So you can't rely only on the primary frequency. Not sure if the data contains the additional frequencies.

It will not

**Comment by daniluk4000** [comment]
Closing this because freq can have multiple controllers
