### ISSUE TITLE
Helicopter icons

### ISSUE THREAD

**Issue by Nyan404** [daniluk4000/vatsim-radar#184]
### Your Vatsim CID

1383795

### What aircraft icon(s) do you suggest to add

Now there is a helicopter icon (namely H160) 
I think it's worth applying it to all other helicopter models.

### Model matching

A109
A119
A129
A139
A149
A2RT
ALH
ALO2
ALO3
AS32
AS3B
AS50
AS55
AS65
B06
B06T
B105
B212
B214
B230
B222
B407
B412
B427
B429
B430
B47G
B47J
BABY
BK17
BRB2
BSTP
CH7
CHIF
COMU
DJIN
DRAG
DYH2
EC20
EC25
EC30
EC35
EC45
EC55
EH10
ELTO
EN28
ES11
EXEC
EXEJ
EXPL
FH11
FREL
GAZL
H12T
H269
H500
H53
H53S
H60
H64
HUCO
K226
K126
KA25
KA26
KA50
KA62
KA52
KMAX
LAMA
LR2T
LYNX
M74
MD52
MD60
MH20
MI10
MI2
MI8
MI24
MI26
MI28
MI34
MI38
NA40
NH90
PSW4
PHIL
PUMA
R22
R4
R44
RMOU
RP1
RVAL
S278
S274
S330
S51
S52
S55P
S58P
S61
S61R
S62
S64
TIGR
UH1
UH12
UH1Y
ULTS
V500
W3
WASP
WG30
X2
X49
YNHL
ZA6

### Validation

- [X] I have searched for other requests and didn't found any alike

**Comment by fdrake97** [comment]
G2CA

**Comment by daniluk4000** [comment]
Dayum, nice
