### ISSUE TITLE
Track line connecting after new connection

### ISSUE THREAD

**Issue by matmaxpilot** [daniluk4000/vatsim-radar#186]
### Your Vatsim CID

Mathias idk my id

### Radar version

0.4.3-beta.2

### Describe your issue

![image](https://github.com/user-attachments/assets/aa54d1c1-f3a9-45a7-bcc7-289c735710d2)
![image](https://github.com/user-attachments/assets/270145f7-b21a-4af5-8cb1-bf8050d58a0e)
lower one without new flightplan
I quickly (1 minute approx) disconnected and connected with a new flightplan and the flight track line connected

### Reproduction steps

Connect and reconnect on same/ different airport with and without new flightplan and change timing

### Platform

opera gx 111.0.5168.61

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned
- [X] I am QA or Patreon member and using next.vatsim-radar.com
- [X] I couldn't reproduce it on production / it's issue in new functionality

**Comment by daniluk4000** [comment]
Should be fixed now
