### ISSUE TITLE
Colour suggestion

### ISSUE THREAD

**Issue by Tushka134** [daniluk4000/vatsim-radar#197]
### Your Vatsim CID

1359973

### Radar version

 v0.4.3-rc.1

### Describe your issue

Just my suggestion for the colours that are used in the radar.
FR24 was my reference, so.

1. All aircraft below 15 feet AGL -- white #ffffff
2. Aircraft from 15 feet AGL to FL80 -- green, but bright #00ff72
3. Aircraft from FL80 to FL110 --  green (???) #00ffd2
4.  Aircraft from FL110 to FL150 -- bright-blue #00a8ff
5. Aircraft from FL150 to FL200 -- blue #0048ff
6. Aircraft from FL200 to FL300 -- dark-blue (idk????) #0030ff
7. Aircraft from FL300 to FL380 -- purpule #6000ff
8. Aircraft from FL380 to FL400 --  bright  purpule #d800ff 
9. Aircraft from FL400 and upper red #ed0705 

### Reproduction steps

none

### Platform

Mozila

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned
- [X] I am QA or Patreon member and using next.vatsim-radar.com
- [X] I couldn't reproduce it on production / it's issue in new functionality

**Comment by daniluk4000** [comment]
We'll stick to another solution, but thanks for this one! If anything, we'll come back to it.
