### ISSUE TITLE
Time not updating in Controller Dashboard

### ISSUE THREAD

**Issue by GabrialGF** [daniluk4000/vatsim-radar#204]
### Your Vatsim CID

1770112

### Radar version

0.4.3

### Describe your issue

In the controller dashboard for KMDW, The time in the top left is not updating. Only way to update it is to refresh the page

### Reproduction steps

Just select KMDW, Select Dashboard, Select Controller View (May be an issue with the dashboard in general, I didn't check)

### Platform

Windows - Chrome

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Should be fixed in production version already .
