### ISSUE TITLE
404 for all airport dashboards.

### ISSUE THREAD

**Issue by reiji69** [daniluk4000/vatsim-radar#212]
### Your Vatsim CID

1679151

### Radar version

0.4.3

### Describe your issue

404 for all airport dashboards.

### Reproduction steps

Click on any airport -> Dashboard -> 404 Page not avail.

### Platform

Windows Chrome Version 126.0.6478.185, iPadOS Chrome version 126.0.6478.153, Safari 17.5, Android Chrome 126.0.6478.186

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Oh shit. Looking at it

**Comment by daniluk4000** [comment]
Fixed

**Comment by reiji69** [comment]
That was fast! Thanks for the website!
