### ISSUE TITLE
KHND Tower does not show up

### ISSUE THREAD

**Issue by the7ferret** [daniluk4000/vatsim-radar#228]
### Your Vatsim CID

1780869

### Radar version

0.4.3

### Describe your issue

When signed on to KHND tower it does not show up...

![image](https://github.com/user-attachments/assets/b8dd669d-01c6-4b68-bfd1-45b213f5c277)
![image](https://github.com/user-attachments/assets/24597806-dd2e-4320-ae77-308b7a038830)

### Reproduction steps

Sign in to the position on CRC

### Platform

Win 10

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Can you please tell me:
- Your callsign as TWR. KHND_TWR?
- Callsign of L30 guy nearby

**Comment by the7ferret** [comment]
Yes HND_TWR, and L30 was LAS_F_APP

You can see it in the messages window of crc on the 2nd image

**Comment by daniluk4000** [comment]
This one is semi-easy, but I can't fix this on my side. 

Opened https://github.com/vatsimnetwork/vatspy-data-project/pull/842

@the7ferret it would be awesome if someone approved from your side can approve this.

**Comment by daniluk4000** [comment]
Once merged and released, you will also show up in both SimAware and VatSpy, not only Radar :)
