### ISSUE TITLE
Incorrect Airport ICAO Code

### ISSUE THREAD

**Issue by JTV13** [daniluk4000/vatsim-radar#236]
### Your Vatsim CID

1634617

### What do you suggest?

Change the ICAO code for East Hampton Airport from it's old one: "KHTO" to show the new one "KJPX".
![Screenshot 2024-08-03 124418](https://github.com/user-attachments/assets/ec687c2b-9ef5-467e-b417-4dd0d98f80bc)

 

### Why do you need that?

This is to reduce confusion for pilots so they have an idea of the correct code they should input into their flight plan.

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
This is sadly an issue for https://github.com/vatsimnetwork/vatspy-data-project
