### ISSUE TITLE
Pause Data updates when tab not in "focus"

### ISSUE THREAD

**Issue by m-9c** [daniluk4000/vatsim-radar#254]
### Your Vatsim CID

974571

### What do you suggest?

When VATSIM Radar is left open in a browser tab, it will continue making calls/receiving data. 

I suggest that the data updates be paused when the tab is not "in focus".

### Why do you need that?

This would reduce the amount of network traffic for both the user individually, and the site overall.

Even if the mechanisms for achieving this aren't perfect, there should still be some reduction in traffic.

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Sorry but no, because we use one connection per multiple tabs in order to save data - and we have no way of knowing you have left all of them.

**Comment by m-9c** [comment]
Thanks for the reply @daniluk4000 . I understand the logic and reasoning.

I was thinking this could be an avenue to reduce some of the network traffic on the server side, but it seems not. :)

**Comment by daniluk4000** [comment]
> Thanks for the reply @daniluk4000 . I understand the logic and reasoning.
> 
> I was thinking this could be an avenue to reduce some of the network traffic on the server side, but it seems not. :)

Yeah we already doing what we can :D
