### ISSUE TITLE
EDGS Label placed wrong

### ISSUE THREAD

**Issue by pa-ulex** [daniluk4000/vatsim-radar#272]
### Your Vatsim CID

1725889

### Radar version

0.4.3

### Describe your issue

The Siegerland (EDGS) is misplaced to aprox. 50.87570532298368, 8.083899008406588. The Airport is at these coords:  50.7072531559601, 8.076191302320831

### Reproduction steps

Anytime EDGS ATIS/AFIS is staffed or a plane is flying in or out of Siegerland.

### Platform

Windows

### Additional info

Was also wrong on the SimAware Map.

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Some of local staff has to correct https://github.com/vatsimnetwork/vatspy-data-project
