### ISSUE TITLE
Potomac Approach (PCT) not showing up

### ISSUE THREAD

**Issue by Vainnor** [daniluk4000/vatsim-radar#96]
### Your Vatsim CID

1652726

### Radar version

v0.4.2-alpha.2

### Describe your issue

Potomac Approach (PCT) is not showing up while it shows up on the reg branch.

Sorry, no pictures.

### Reproduction steps

Open next.vatsim-radar.com when PCT is online. Only ATIS will show and no PCT. 

Open vatsim-radar.com when PCT is online. PCT will be displayed

### Platform

Windows, Brave Version 1.67.119 Chromium: 126.0.6478.114 (Official Build) (64-bit)

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned
- [X] I am QA or Patreon member and using next.vatsim-radar.com
- [X] I couldn't reproduce it on production / it's issue in new functionality

**Comment by Vainnor** [comment]
https://i.imgur.com/CjFaz8h.png

https://i.imgur.com/gKhmdhL.png

**Comment by daniluk4000** [comment]
Please tell me the callsign

**Comment by Vainnor** [comment]
Should be PCT_APP

**Comment by daniluk4000** [comment]
Is this normal when both PCT_APP and IAD_M_APP are available?

![image](https://github.com/daniluk4000/vatsim-radar/assets/10450717/de1c69fc-8b7e-4996-a42e-170cf7f40312)
